name: Build & Push ComfyUI to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build y Push de la imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/comfyui-client:latest
          no-cache: true
